version: "3"

services:
  app:
    build:
      context: .
    container_name: fastapi-app
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=sqlite:///./app.db
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: nouchka/sqlite3 # Placeholder for SQLite in Docker; update if using another DB
    container_name: sqlite-db
    volumes:
      - db_data:/var/lib/sqlite3

volumes:
  db_data:

